//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBSDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayRequest
    {
        public int ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> Feasible { get; set; }
        public int UserID { get; set; }
        public int RequestStatusID { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
    
        public virtual User User { get; set; }
        public virtual StatusRequest StatusRequest { get; set; }
    }
}
