//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public byte[] Pwd { get; set; }
        public byte[] PwdSalt { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
    }
}
